import { chmodSync, existsSync, copyFileSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import chalk from 'chalk';
import { stringify as stringifyYaml } from 'yaml';
import type { WizardStep, WizardContext } from '../types.js';
import type { AppConfig, UserConfig, ExporterEntry } from '../../config/schema.js';
import { createAppConfigSchema, formatConfigError } from '../../config/schema.js';
import { atomicWrite } from '../../config/write.js';
import { sectionBox, success, error, dim } from '../ui.js';
import { cliCommand } from '../../cli-invocation.js';
import { mergeIntoYaml } from '../yaml-merge.js';
import { renderConfigDiff } from '../config-diff.js';
import { appendEnvFile } from '../../config/env-file.js';
import { envPathFor } from '../../config/paths.js';
import { errMsg } from '../../utils/error.js';
import {
  configPathKey,
  referencedEnvNames,
  resolveEnvReferencesTracked,
} from '../../config/env-refs.js';
import { safeParseResolved } from '../../config/env-coerce.js';

const YAML_HEADER = `# BLE Scale Sync - config.yaml
# Generated by: ${cliCommand('setup')}
#
# WARNING: This file may contain sensitive data (passwords, tokens).
# Use \${ENV_VAR} references for secrets (resolved from .env at load time).
#
# Validate: ${cliCommand('validate')}
# Edit:     ${cliCommand('setup')} (edit mode)
`;

function stripWizardFields(config: Partial<AppConfig>): Record<string, unknown> {
  return { ...config };
}

/**
 * A multi-user setup picks the user by weight, so a reading outside every
 * user's range (a misread, or a spoofed broadcast frame) would still be
 * exported to the nearest user under the schema default `warn`. The wizard
 * writes `skip` for such a setup. The schema default stays `warn`, and a value
 * the config already carries is never overridden.
 */
function outOfRangeDefault(config: Partial<AppConfig>): Pick<Partial<AppConfig>, 'out_of_range'> {
  if (config.out_of_range !== undefined) return {};
  return (config.users?.length ?? 0) > 1 ? { out_of_range: 'skip' } : {};
}

function printSummary(config: Partial<AppConfig>): void {
  // Users section
  const users = config.users ?? [];
  const userLines: string[] = [];
  for (const u of users) {
    const user = u as UserConfig;
    const range = user.weight_range
      ? chalk.dim(` [${user.weight_range.min}\u2013${user.weight_range.max} kg]`)
      : '';
    const own = (user.exporters ?? []).map((e) => (e as ExporterEntry).type);
    const exporterInfo = own.length > 0 ? chalk.dim(` + ${own.join(', ')}`) : '';
    userLines.push(
      `${chalk.bold(user.name)} ${chalk.dim(`(${user.slug})`)}${range}${exporterInfo}`,
    );
  }
  console.log('\n' + sectionBox(`Users (${users.length})`, userLines.join('\n')));

  // BLE
  const mac = config.ble?.scale_mac;
  const handler = config.ble?.handler ?? 'auto';
  const bleText =
    `${chalk.bold('handler:')} ${handler}` +
    `, ${mac ? `${chalk.bold('scale_mac:')} ${mac}` : dim('auto-discovery')}`;
  console.log(sectionBox('BLE', bleText));

  // Scale
  const scale = config.scale;
  if (scale) {
    console.log(
      sectionBox(
        'Scale',
        `weight_unit=${chalk.bold(scale.weight_unit)}, height_unit=${chalk.bold(scale.height_unit)}`,
      ),
    );
  }

  // Global exporters
  const globalExporters = config.global_exporters ?? [];
  const exporterLines =
    globalExporters.length === 0
      ? dim('(none)')
      : globalExporters.map((e) => `- ${(e as ExporterEntry).type}`).join('\n');
  console.log(sectionBox(`Global Exporters (${globalExporters.length})`, exporterLines));

  // Runtime
  const rt = config.runtime;
  if (rt) {
    const rtText = `continuous=${chalk.bold(String(rt.continuous_mode))}, cooldown=${chalk.bold(`${rt.scan_cooldown}s`)}, dry_run=${chalk.bold(String(rt.dry_run))}`;
    console.log(sectionBox('Runtime', rtText));
  }
}

/**
 * The config with every `${VAR}` that resolves replaced by its value, plus the
 * paths whose whole value was one reference, for validation only. The app
 * validates resolved values, so `weight_unit: ${UNIT}` loads fine but failed
 * here and the save needed "Save anyway?". A variable that is not defined
 * stays as written, which is how everything was validated before.
 */
function resolveForValidation(
  value: unknown,
  path: (string | number)[] = [],
  wholeRefs: Map<string, string> = new Map(),
): { value: unknown; wholeRefs: Map<string, string> } {
  if (typeof value === 'string') {
    try {
      const leaf = resolveEnvReferencesTracked(value);
      const name = leaf.wholeRefs.get(configPathKey([]));
      if (name !== undefined) wholeRefs.set(configPathKey(path), name);
      return { value: leaf.value, wholeRefs };
    } catch {
      return { value, wholeRefs };
    }
  }
  if (Array.isArray(value)) {
    return {
      value: value.map((v, i) => resolveForValidation(v, [...path, i], wholeRefs).value),
      wholeRefs,
    };
  }
  if (value !== null && typeof value === 'object') {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(value)) {
      out[k] = resolveForValidation(v, [...path, k], wholeRefs).value;
    }
    return { value: out, wholeRefs };
  }
  return { value, wholeRefs };
}

/**
 * The text to write. An edit keeps the file it edits, comments included; a
 * fresh setup (or a file that is not a YAML mapping) gets a new one.
 */
function serialize(ctx: WizardContext, finalConfig: Record<string, unknown>): string {
  if (ctx.isEditMode && existsSync(ctx.configPath)) {
    try {
      const merged = mergeIntoYaml(readFileSync(ctx.configPath, 'utf8'), finalConfig);
      if (merged !== undefined) return merged;
    } catch {
      // Unreadable now: write it fresh, as before.
    }
  }
  return YAML_HEADER + '\n' + stringifyYaml(finalConfig, { lineWidth: 0 });
}

/**
 * What the save will change. In edit mode the settings of the file on disk
 * against the text about to replace it, so a section visited "just to look"
 * that changed a value shows up before it is written. A fresh setup over an
 * existing file replaces it whole, which a diff would only bury.
 */
function printChanges(ctx: WizardContext, yamlContent: string): void {
  if (!existsSync(ctx.configPath)) return;
  if (!ctx.isEditMode) {
    console.log(
      `\n  ${dim(`This replaces the existing ${ctx.configPath} (the old one is kept as .bak).`)}`,
    );
    return;
  }
  let before: string;
  try {
    before = readFileSync(ctx.configPath, 'utf8');
  } catch {
    return;
  }
  const diff = renderConfigDiff(before, yamlContent);
  if (diff === null) {
    console.log(`\n  ${dim('No changes to config.yaml.')}`);
    return;
  }
  const paint = (l: string): string =>
    l.startsWith('+')
      ? chalk.green(l)
      : l.startsWith('-')
        ? chalk.red(l)
        : l.startsWith('~')
          ? chalk.yellow(l)
          : dim(l);
  console.log('\n' + sectionBox('Changes (secrets hidden)', diff.map(paint).join('\n')));
}

export const summaryStep: WizardStep = {
  id: 'summary',
  title: 'Review & Save',
  order: 80,

  async run(ctx: WizardContext): Promise<void> {
    ctx.saved = false;
    printSummary(ctx.config);

    // Ensure required fields have defaults
    const finalConfig = {
      version: 1 as const,
      scale: { weight_unit: 'kg' as const, height_unit: 'cm' as const },
      unknown_user: 'nearest' as const,
      ...outOfRangeDefault(ctx.config),
      ...stripWizardFields(ctx.config),
    };

    // Validate with Zod before saving
    const resolved = resolveForValidation(finalConfig);
    const result = safeParseResolved(
      createAppConfigSchema(dirname(resolve(ctx.configPath))),
      resolved.value,
      resolved.wholeRefs,
    );
    if (!result.success) {
      console.log(`\n  ${error('Validation errors:')}\n`);
      console.log(formatConfigError(result.error));
      const saveAnyway = await ctx.prompts.confirm('Save anyway? (config may not load correctly)', {
        default: false,
      });
      if (!saveAnyway) {
        console.log('  Not saved.');
        return;
      }
    }

    const yamlContent = serialize(ctx, finalConfig);
    printChanges(ctx, yamlContent);

    const save = await ctx.prompts.confirm(`Save to ${ctx.configPath}?`, { default: true });
    if (!save) {
      console.log('  Not saved.');
      return;
    }

    // Secrets the person chose to keep in .env go there first: the config
    // refers to them by name, and a config saved without them would not load.
    // Only the ones it still refers to: a secret typed again (stored under a
    // new name) or one whose exporter was removed would otherwise end up in
    // .env with nothing reading it.
    const referenced = referencedEnvNames(finalConfig);
    const envEntries = new Map(
      [...(ctx.pendingEnv ?? [])].filter(([name]) => referenced.has(name)),
    );
    if (envEntries.size > 0) {
      const envPath = envPathFor(ctx.configPath);
      try {
        const written = appendEnvFile(envPath, envEntries);
        if (written.length > 0) {
          console.log(`\n  ${success(`Added ${written.join(', ')} to ${envPath}`)}`);
        }
      } catch (err) {
        console.log(`\n  ${error(`Could not write ${envPath}: ${errMsg(err)}`)}`);
        console.log('  Not saved: config.yaml would refer to variables that are not set.');
        return;
      }
    }

    // Backup existing config before overwriting
    if (existsSync(ctx.configPath)) {
      try {
        copyFileSync(ctx.configPath, ctx.configPath + '.bak');
      } catch {
        // Non-fatal — backup may fail on some filesystems
      }
    }

    // Write atomically
    atomicWrite(ctx.configPath, yamlContent);
    ctx.saved = true;
    ctx.pendingEnv?.clear();

    // Restrict permissions on Linux/macOS
    if (ctx.platform.os === 'linux' || ctx.platform.os === 'darwin') {
      try {
        chmodSync(ctx.configPath, 0o600);
      } catch {
        // Non-fatal — may fail on some filesystems
      }
    }

    console.log(`\n  ${success(`Saved to ${ctx.configPath}`)}`);

    // Next steps
    // Built from how this process was started: an npm-installed user has no
    // package.json to run `npm start` against, and a clone has no
    // `ble-scale-sync` on PATH.
    const run = cliCommand();
    const nextSteps = [
      `${chalk.bold(run)}  ${dim('# Run once')}`,
      `${chalk.bold(`CONTINUOUS_MODE=true ${run}`)}  ${dim('# Run in continuous mode')}`,
      `${chalk.bold(cliCommand('validate'))}  ${dim('# Validate your config')}`,
      `${chalk.bold(cliCommand('setup'))}  ${dim('# Edit configuration')}`,
    ];

    console.log('\n' + sectionBox('Next Steps', nextSteps.join('\n')));
  },
};

// Exported for testing
export { stripWizardFields, printSummary, YAML_HEADER };
